### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jansaternus** [ange-yaghi/engine-sim#275] opened 2022-09-12 17:44 UTC
When i tried to build the project it failed to find "malloc.h". Where do i find it or get it?

**Comment by jansaternus** [comment] 2022-09-15 13:14
Some info

[  0%] Built target csv-io
[  0%] Building CXX object dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/src/yds_animation_action.cpp.o
In file included from /Users/***/engine-sim/dependencies/submodules/delta-studio/src/yds_animation_action.cpp:1:
In file included from /Users/***/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_animation_action.h:4:
In file included from /Users/***/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_base.h:4:
In file included from /Users/***/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_dynamic_array.h:5:
/Users/***/engine-sim/dependencies/submodules/delta-studio/src/../include/yds_allocator.h:4:10: fatal error: 
      'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/src/yds_animation_action.cpp.o] Error 1
make[1]: *** [dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/all] Error 2
make: *** [all] Error 2

**Comment by Jckf** [comment] 2022-09-21 11:49
Duplicate of https://github.com/ange-yaghi/engine-sim/issues/12

ES (officially) only supports Windows.

**Closed by Jckf** 2022-09-21 11:49 UTC
Labels: support
