### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Necro1423** [ange-yaghi/engine-sim#269] opened 2022-09-11 04:43 UTC
I been trying to startup the game and it crash, and i don't know why, It doesn't say anything when it crashes, just the typical message from Windowy.
My pc specs:
Windows 7 ultimate x64
3.75gb ram
Amd Sempron 2.71ghz
Integrated card graphics
yea my pc it's a dinosaur, is from 2006

**Comment by NomsterDude** [comment] 2022-09-12 03:45
Similar to issue #27?

**Comment by Jckf** [comment] 2022-09-12 13:59
Yup, closing as duplicate of #27.

**Closed by Jckf** 2022-09-12 13:59 UTC
