### ISSUE TITLE
The program barely use cpu

### ISSUE THREAD

**Issue by KReshi0** [ange-yaghi/engine-sim#211] opened 2022-08-31 06:50 UTC
I noticed that the program mainly use cpu, but it not using more than 20% on my laptop.

The sound repeat is still happening. Lowering simulation speed doesn't help much.

Cpu is Ryzen 7 3750H

![image](https://user-images.githubusercontent.com/89409037/187612259-3cd8ff27-4956-4c25-ab3c-bc3c11e9b237.png)

**Comment by Milut** [comment] 2022-08-31 08:07
Probably because it uses only one CPU thread. I think that for now it is just a design limitation

**Comment by Calinou** [comment] 2022-08-31 15:19
Duplicate of https://github.com/ange-yaghi/engine-sim/issues/87.

**Closed** 2022-08-31 15:30 UTC
