### ISSUE TITLE
running the .exe and refuses to start

### ISSUE THREAD

**Issue by crypto99999** [ange-yaghi/engine-sim#244] opened 2022-09-04 05:25 UTC
dont know if im missing something thats required but im just running the .exe file and nothing happens. also im on 64 bit windows 10 with 16gb ram if that helps

**Comment by LexonBlackzz** [comment] 2022-09-04 16:17
Do you have an engine specified in main.mr?

**Comment by crypto99999** [comment] 2022-09-05 03:31
> 

no but if you or anyone else could point me towards one id love that very much :)

**Comment by LexonBlackzz** [comment] 2022-09-05 05:16
Use the [Engine importer](https://github.com/ange-yaghi/engine-sim/wiki/Community-projects#engine-importer), and import an engine

**Comment by Jckf** [comment] 2022-09-05 14:07
Are you having trouble running a clean copy of the sim, where you have made zero changes, or did you alter any of the scripts and now it fails to start? Does the sim open for a second before closing, or does nothing happen on screen at all?

**Comment by crypto99999** [comment] 2022-09-05 19:46
> 

clean copy and nothing happens when trying to run, doesnt start

**Comment by NomsterDude** [comment] 2022-09-08 17:47
> Are you having trouble running a clean copy of the sim, where you have made zero changes, or did you alter any of the scripts and now it fails to start? Does the sim open for a second before closing, or does nothing happen on screen at all?

For me, when I run the sim it shows a white screen for one second and then disappears.

**Comment by Jckf** [comment] 2022-09-08 18:02
Closing as presumed duplicate of https://github.com/ange-yaghi/engine-sim/issues/27

**Closed by Jckf** 2022-09-08 18:02 UTC
Labels: support
