### ISSUE TITLE
quick reload (F5)?

### ISSUE THREAD

**Issue by H3nr1ks-C0d3** [ange-yaghi/engine-sim#120] opened 2022-08-17 22:36 UTC
Fine-Tuning camshafts can be annoying. the program starts quite quickly so how about implementing a full reload(F5) so I don't have to alt-tab into my explorer to open the exe.

cheers

**Comment by Jckf** [comment] 2022-08-17 22:39
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/59

**Closed by Jckf** 2022-08-17 22:39 UTC
