### ISSUE TITLE
Crashes with no error code.

### ISSUE THREAD

**Issue by boomaboom0818** [ange-yaghi/engine-sim#209] opened 2022-08-31 00:15 UTC
I downloaded a fresh new copy and I checked all the import paths and they all seem to be alright. but it instantly crashes when I open the application.

**Comment by Jckf** [comment] 2022-08-31 15:31
Is there anything in error_log.log?

**Comment by XxEduardoMTz** [comment] 2022-08-31 18:10
having the same problem! And no, error_lo.log is blank.

**Comment by quinnzaballa** [comment] 2022-09-01 04:02
Do you use custom engine *.mr?

**Comment by boomaboom0818** [comment] 2022-09-01 10:15
I didn't change anything yet. Its a fresh new copy

**Comment by haohaoh4** [comment] 2022-09-04 08:09
Same problem. There is even nothing in error log.

**Comment by NomsterDude** [comment] 2022-09-08 17:49
Same problem, blank error_log.txt

**Comment by Jckf** [comment] 2022-09-08 18:00
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27

**Closed by Jckf** 2022-09-08 18:00 UTC
Labels: support
