### ISSUE TITLE
Game starts with white screen then closes with no error log

### ISSUE THREAD

**Issue by MotherofaDuck** [ange-yaghi/engine-sim#249] opened 2022-09-05 20:58 UTC
Fresh install of game, vulkan-1.dll added but the game starts with a white screen before closing after 1 second
![Screenshot (3)](https://user-images.githubusercontent.com/90338074/188511745-50b3155d-8ae9-4c79-96a9-85a7ad45b6b4.png)
and the error log is empty
![errorllog](https://user-images.githubusercontent.com/90338074/188511793-6de4a15a-f101-408b-aa12-07ebbcf3b6bd.png)
Windows Event Viewer tells me that the program closed with error 0xc0000005(Access Violation)
I tried running every version but they always crash
Any fix for this?

**Comment by Jckf** [comment] 2022-09-06 10:19
Just a note after talking to @MotherofaDuck and a couple other on Discord: The common theme with these types of crashes appear to be that they're all using old integrated graphics.

**Comment by MotherofaDuck** [comment] 2022-09-06 11:47
So the game doesnt work on old graphic cards?

**Comment by NomsterDude** [comment] 2022-09-08 18:01
Same problem here!

**Comment by Jckf** [comment] 2022-09-08 18:02
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27

**Closed by Jckf** 2022-09-08 18:02 UTC
Labels: bug
