### ISSUE TITLE
App does not start 

### ISSUE THREAD

**Issue by Diougo** [ange-yaghi/engine-sim#133] opened 2022-08-20 11:49 UTC
When i start the app it just closes, and i dont get any error in  the error log file.

**Comment by HawkHunt** [comment] 2022-08-20 16:12
Did you modify any files or is it  "clean"?

**Comment by Diougo** [comment] 2022-08-20 16:32
> Did you modify any files or is it "clean"?

It´s a clean install.

**Comment by sujaldev** [comment] 2022-08-21 06:47
If you post your system specifications, that might be helpful

**Comment by Diougo** [comment] 2022-08-23 15:37
i7-8650U
16gb ram
gtx 1060 6gb

**Comment by Diougo** [comment] 2022-08-23 15:39
> If you post your system specifications, that might be helpful

i7-8650U
16gb ram
gtx 1060 6gb

**Comment by sujaldev** [comment] 2022-08-23 16:42
OS?

**Comment by Diougo** [comment] 2022-08-23 16:44
> OS?

Windows 11 Pro version 21H2

**Comment by sujaldev** [comment] 2022-08-23 16:47
does the error log file have anything?

**Comment by Diougo** [comment] 2022-08-23 16:48
> does the error log file have anything?
It has nothing.

**Comment by Jaxeman09** [comment] 2022-09-04 09:26
> > does the error log file have anything?
> 
> It has nothing.

When you open it does it say there is a missing file or does it just not open???

**Comment by lepton0004** [comment] 2022-09-04 09:59
does nothing. it peeks then sleeps

**Comment by Jckf** [comment] 2022-09-08 18:00
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27

**Closed by Jckf** 2022-09-08 18:00 UTC
Labels: support
