### ISSUE TITLE
Everything breaks

### ISSUE THREAD

**Issue by gameninjayt** [ange-yaghi/engine-sim#258] opened 2022-09-07 06:38 UTC
![Screenshot 2022-09-07 083707](https://user-images.githubusercontent.com/113009094/188806328-9c2ff8e6-936c-4fc6-8699-f5a6d5da3bcd.png)
When you adjust the hold rpm there is no upper limit so when you get to 50k rpm everything just breaks

**Comment by GoostYTQC** [comment] 2022-09-07 07:52
So y going to 50k if you it will break l, like I understand it's a bug but there not a lot of people using this future and it don't really make sense to fix it

**Comment by Jckf** [comment] 2022-09-07 15:00
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/197

**Closed by Jckf** 2022-09-07 15:00 UTC
