### ISSUE TITLE
Add Controller Support

### ISSUE THREAD

**Issue by P13rlU** [ange-yaghi/engine-sim#285] opened 2022-09-17 08:47 UTC
Would be nice to implement xinput or playinput for the simulator, the major advantage would be with the triggers, because they have a variable input, instead of pressi shift + space for smooth clutch

**Comment by Jckf** [comment] 2022-09-20 00:31
Duplicate of https://github.com/ange-yaghi/engine-sim/issues/36

**Closed by Jckf** 2022-09-20 00:31 UTC
