### ISSUE TITLE
Simulator crashes after displaying blank white screen.

### ISSUE THREAD

**Issue by NomsterDude** [ange-yaghi/engine-sim#263] opened 2022-09-08 17:58 UTC
I have a fresh download of the v1.10 build folder.

When I run it, the file instantly opens up a window with a blank white screen. This screen shows up for 2 seconds roughly before it closes.

The error_log.txt file is blank, no changes have been made.

**Comment by Jckf** [comment] 2022-09-08 18:02
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27

**Closed by Jckf** 2022-09-08 18:02 UTC
