### ISSUE TITLE
Problem with the boot 

### ISSUE THREAD

**Issue by estebanchd23** [ange-yaghi/engine-sim#318] opened 2022-09-30 17:11 UTC
Hello, first, I am french so excuse me for my bad english

I have a laptop running on win10 and no graphics card and i try several time to boot the program,
the first problem i have was the .dll problem, solved with upgrading directX drivers;
but now the programm succesfuly boot but for a very short time (1 second or less), with white screen and close by itself (but never i have lose performances while booting program)
no error screen come out so i don't find any solution.
it is a problem of too weak pc or i have missed something ?
thank you for your patience
P.s. : i use the latest version of the program 0.1.11a

**Comment by antmagl** [comment] 2022-09-30 20:16
Same problem, even the developer doesn't know how to fix it

**Comment by Jckf** [comment] 2022-10-01 11:07
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/27

We don't currently know what is causing this problem.

**Closed by Jckf** 2022-10-01 11:07 UTC
