### ISSUE TITLE
engine sim is taking global input

### ISSUE THREAD

**Issue by alec-jensen** [ange-yaghi/engine-sim#11] opened 2022-08-10 14:16 UTC
so the app is taking input, even when its not in focus. i feel like it should only accept input if it is in focus.

**Comment by ange-yaghi** [comment] 2022-08-11 22:14
I'll disable global inputs, I needed it for my own purposes but I can imagine it being annoying for other people

**Comment by naikrovek** [comment] 2022-08-11 22:40
Duplicate of #4.  Can issues be merged?

**Comment by ange-yaghi** [comment] 2022-08-12 07:47
Should be fixed now.

**Closed by ange-yaghi** 2022-08-12 07:47 UTC
