### ISSUE TITLE
Build Error:  'malloc.h' file not found

### ISSUE THREAD

**Issue by yasinarik** [ange-yaghi/engine-sim#12] opened 2022-08-10 14:22 UTC
What a fascinating project! Thanks for making it public. I immediately wanted to try it out!

However, I am not familiar with C++ so it might be because of my lack of experience.

I have followed the instructions I get an error like that:

```
fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^~~~~~~~~~
1 error generated.
make[2]: *** [dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/src/yds_animation_action.cpp.o] Error 1
make[1]: *** [dependencies/submodules/delta-studio/CMakeFiles/delta-core.dir/all] Error 2
make: *** [all] Error 2
```

I am using **macOS** btw. 

When I do a search about `#include <malloc.h>` I see that people suggest just using `#include <stdlib.h>` instead.

The error happens on this file: 
`dependencies/submodules/delta-studio/include/yds_allocator.h`

How to resolve this issue?

**Comment by BoogieHasFun** [comment] 2022-08-10 16:47
The app is only available for windows, you might be able to compile it but if you are trying to compile it to use the application on MacOS then you're wasting time.

**Comment by BoogieHasFun** [comment] 2022-08-10 18:37
on line 40 of the read me it states "Note: this project currently only builds on Windows!"

**Comment by BoogieHasFun** [comment] 2022-08-10 18:44
if your desperate to try it out you can always use a windows [virtual machine (intel macbooks only)](https://www.vmware.com/go/getfusionplayer)

**Comment by ange-yaghi** [comment] 2022-08-11 22:16
We have some people working on a Linux port and there may be a Mac port at some point, but at the moment it only natively supports Windows.

**Comment by bsharper** [comment] 2022-08-12 17:06
@BoogieHasFun FYI there's also UTM (https://mac.getutm.app/), which allows you to run x86 on M1-based Macs (and some ARM64 OSes on x86). It's free and open-source. There is some performance loss, but I was surprised at how responsive W10 x64 was on an M1 running under UTM.

**Comment by yasinarik** [comment] 2022-08-12 17:14
> @BoogieHasFun FYI there's also UTM (https://mac.getutm.app/), which allows you to run x86 on M1-based Macs (and some ARM64 OSes on x86). It's free and open-source. There is some performance loss, but I was surprised at how responsive W10 x64 was on an M1 running under UTM.

Wow this is the reward of the day! Thanks a lot. I will probably need UTM anyways for other things to test on Windows! Appreciated:)

**Comment by BoogieHasFun** [comment] 2022-08-12 17:39
> @BoogieHasFun FYI there's also UTM ([mac.getutm.app](https://mac.getutm.app/)), which allows you to run x86 on M1-based Macs (and some ARM64 OSes on x86). It's free and open-source. There is some performance loss, but I was surprised at how responsive W10 x64 was on an M1 running under UTM.

i forgot about UTM

**Comment by gbwiersum** [comment] 2022-08-17 17:11
It's possible just changing to stdlib.h will solve the issue. I'll see if I have time to try it out but any other mac user might get to it before me.

**Comment by preland** [comment] 2022-08-29 14:07
I am also interested in getting this to build on Mac (even if the end build will still only be usable via a wine bottle or a VM). Will see what further issues appear other than malloc.h.

**Comment by andreyluiz** [comment] 2022-08-30 19:39
@gbwiersum That's not the only needed change. I'm on Mac-M1 and get `error: use of undeclared identifier '__builtin_ia32_punpckhwd'`. There is more stuff to be changed.

**Comment by andreyluiz** [comment] 2022-08-30 20:28
@bsharper UTM also doesn't work very well. The processing power is not near sufficient to run the simulator efficiently. Also, there are plenty of issues with the UI and the shortcuts (some keys won't respond to key up). So I think it's not an option as well.

**Comment by Simsalaba** [comment] 2022-09-21 11:05
worked on parallels desktop for me but the performance is not good enough

**Comment by Jckf** [comment] 2022-10-01 11:04
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/2

**Closed by Jckf** 2022-10-01 11:04 UTC
