### ISSUE TITLE
feature request: easier way to change engines

### ISSUE THREAD

**Issue by fazbeark1ng** [ange-yaghi/engine-sim#121] opened 2022-08-17 22:50 UTC
if this is not possible than ok but i was trying to change engines and it made no sense to me

**Comment by Jckf** [comment] 2022-08-17 23:07
There's a guide on how to change the engine in [our FAQ](https://github.com/ange-yaghi/engine-sim/wiki/Frequently-Asked-Questions).

I'm closing this ticket, as it is a duplicate of https://github.com/ange-yaghi/engine-sim/issues/59.

**Closed by Jckf** 2022-08-17 23:07 UTC
