### ISSUE TITLE
Keystrokes not read when using remote control software

### ISSUE THREAD

**Issue by ffredyk** [ange-yaghi/engine-sim#117] opened 2022-08-17 10:38 UTC
I think the code for reading and parsing keystrokes doesn't work with remote desktop software. Keystrokes are not picked up using either Windows RDP or Parsec

**Comment by Jckf** [comment] 2022-08-17 21:39
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/99

**Closed by Jckf** 2022-08-17 21:39 UTC
