### ISSUE TITLE
my game crash after a few second i open it:(

### ISSUE THREAD

**Issue by dat0207** [ange-yaghi/engine-sim#238] opened 2022-09-03 15:09 UTC
pls help me,i really like and impressed with this game

**Comment by Jckf** [comment] 2022-09-03 16:47
Have you made any changes to the game files, or is this a fresh copy?

**Comment by dat0207** [comment] 2022-09-04 02:23
I didn't do anything to the game yet

**Comment by NomsterDude** [comment] 2022-09-08 17:54
I have a fresh copy and it shows a blank white screen before crashing. Blank error log.

**Comment by Jckf** [comment] 2022-09-08 18:01
Closing as presumed duplicate of https://github.com/ange-yaghi/engine-sim/issues/27

**Closed by Jckf** 2022-09-08 18:01 UTC
Labels: support
