### ISSUE TITLE
Vehicle speed unit

### ISSUE THREAD

**Issue by KILLERMANTV** [ange-yaghi/engine-sim#102] opened 2022-08-15 17:40 UTC
How would you change vehicle speed from mph to kmh ?

**Comment by TheMispeled** [comment] 2022-08-16 18:31
Hi, copy of #66 .

**Comment by Jckf** [comment] 2022-08-17 21:46
Closing as duplicate of https://github.com/ange-yaghi/engine-sim/issues/66

**Closed by Jckf** 2022-08-17 21:46 UTC
