### ISSUE TITLE
Game crashes after a few seconds with a white screen

### ISSUE THREAD

**Issue by antmagl** [ange-yaghi/engine-sim#292] opened 2022-09-21 16:41 UTC
Hi, i really want to try this game but it crashes 2 seconds after opening.
Nothing in the error log shows up.

**Comment by ange-yaghi** [comment] 2022-09-22 19:25
I have not been able to replicate this issue on any testing computer I have. The only way that this can be fixed right now is if someone volunteers some time to try debugging this on their own computers. Other than that, there's not much I can do

**Comment by LombaCZ** [comment] 2022-09-22 20:58
Hi, I have same problem. 
Newly installed Win10 + fresh graphic card drivers. 
I tried copy/paste engine-sim-build to Program Files (x86). Installed Visual studio with C++. Run as Administrator.
Did not make difference. I have time to try anything else but I am noob at coding. I could also share my desktop if that would help.

**Comment by Jckf** [comment] 2022-09-22 22:25
Closing as duplicate of #27.

**Closed by Jckf** 2022-09-22 22:25 UTC
